// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd-rv6UugFQ5S9kZplTk-QZgudIe1eBao',
    appId: '1:604537597515:web:cca7d5d89bf9197f01a7ce',
    messagingSenderId: '604537597515',
    projectId: 'local-walker-91486',
    authDomain: 'local-walker-91486.firebaseapp.com',
    storageBucket: 'local-walker-91486.firebasestorage.app',
    measurementId: 'G-B3T1R16PRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-wNcV7qCXco0ya-NYHt2Ioq29iUAJ4uU',
    appId: '1:604537597515:android:31346fb59e4ad80f01a7ce',
    messagingSenderId: '604537597515',
    projectId: 'local-walker-91486',
    storageBucket: 'local-walker-91486.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj6HaB5UYhH8G8XMwSfp3Au3t-8Nl7oEo',
    appId: '1:604537597515:ios:70f1d6516e5e712a01a7ce',
    messagingSenderId: '604537597515',
    projectId: 'local-walker-91486',
    storageBucket: 'local-walker-91486.firebasestorage.app',
    iosClientId: '604537597515-43cmu3spu5fmdeqf28lt31p74d4bttnt.apps.googleusercontent.com',
    iosBundleId: 'com.example.localWalker',
  );

}