// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABwm5hDTqHeR7c961cYGDop1jjq4xv8FI',
    appId: '1:978249326561:web:1188f2a78cc806aeca7ca0',
    messagingSenderId: '978249326561',
    projectId: 'local-walker',
    authDomain: 'local-walker.firebaseapp.com',
    storageBucket: 'local-walker.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrj7N6kAuJVYBWFcQQhgIZZ3b7S_ACOhc',
    appId: '1:978249326561:android:b34bc85cc8d60345ca7ca0',
    messagingSenderId: '978249326561',
    projectId: 'local-walker',
    storageBucket: 'local-walker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAypBu5fF00Y3VS8ltVLou8a_h_2FlmG58',
    appId: '1:978249326561:ios:b2be78473e0db9a7ca7ca0',
    messagingSenderId: '978249326561',
    projectId: 'local-walker',
    storageBucket: 'local-walker.appspot.com',
    iosBundleId: 'com.example.localwalker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAypBu5fF00Y3VS8ltVLou8a_h_2FlmG58',
    appId: '1:978249326561:ios:7c81ca78d03438edca7ca0',
    messagingSenderId: '978249326561',
    projectId: 'local-walker',
    storageBucket: 'local-walker.appspot.com',
    iosBundleId: 'com.example.localwalker.RunnerTests',
  );
}
